services:
  app:
    build:
      context: ./
      dockerfile: dev.dockerfile
    image: dev-acme-hbm-plus
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
