services:
  app:
    build:
      context: ./
      dockerfile: dev.dockerfile
    image: dev-acme-hbm-plus
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: sync+restart
          path: ./conf/.env.development
          target: /app/.env
        - action: rebuild
          path: ./package.json
    depends_on:
      database-starter:
        condition: service_completed_successfully
      pushpin:
        condition: service_started

  mongodb:
    container_name: database
    image: mongo:7.0.6-jammy
    restart: always
    volumes:
      - ./conf/init-database.sh:/scripts/init-database.sh

  database-starter:
    image: docker
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      mongodb:
        condition: service_started
    command: docker exec database /scripts/init-database.sh

  pushpin:
    image: fanout/pushpin:1.39.1
    environment:
      target: app
    ports:
      - 4000:7999
